engineer:
  timeout: 1.0
  chassis:
    x_coeff: 2.0
    y_coeff: 2.0
    z_mk_coeff: 300
    z_rc_coeff: 3.0
    x_accel_set : 4
    y_accel_set : 4
    z_accel_set : 10

  gimbal:
    yaw_coeff : 0.0025
    pitch_mk_coeff : 0.05
    pitch_rc_coeff : 0.01
    yaw_left_limit: -1.57
    yaw_right_limit: 1.57
    pitch_low_limit: -0.52
    pitch_high_limit: 0.52
   
    
