infantry:
  chassis:
    x_coeff: 2.5
    y_coeff: 2.5
    gyro_vel: 4
    x_accel_set : 7
    y_accel_set : 7
    z_accel_set : 8
  gimbal:
    yaw_mk_coeff : 0.2
    yaw_rc_coeff : 0.005
    pitch_mk_coeff : 0.2
    pitch_rc_coeff : 0.005

    
