joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 300
arm:
  arm_joint_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    gains:
      joint1: { p: 5.0, i: 0.6, d: 0.1, i_clamp: 4.0 }
      joint2: { p: 200.0, i: 1.2, d: 0.3, i_clamp: 4.0 }
      joint3: { p: 40.0, i: 0.4, d: 0.15, i_clamp: 4.0 }
      joint4: { p: 3.0, i: 0.1, d: 0.1, i_clamp: 4.0 }
      joint5: { p: 4.0, i: 0.8, d: 0.15, i_clamp: 4.0 }
      joint6: { p: 3.0, i: 0.1, d: 0.0, i_clamp: 4.0 }

  arm_gripper_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - joint7
    gains:
      joint7: { p: 250, i: 2.0, d: 0.0, i_clamp: 4.0 }
