controller_list:
  - name: fake_manipulator_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1_left
      - joint2_left
      - joint3_left
      - joint4
      - joint5
      - joint6
      - joint7
initial:  # Define initial robot poses per group
#  - group: manipulator
#    pose: home

  []