arm:
    # Publish all joint states
        joint_state_controller:
                type: joint_state_controller/JointStateController
                publish_rate: 100

    # Position Controllers
        joint1_position_controller:
               type: effort_controllers/JointPositionController
               joint: Joint_1
               pid: {p: 100, i: 0.01, d: 10.0}
        joint2_position_controller:
               type: effort_controllers/JointPositionController
               joint: Joint_2
               pid: {p: 100, i: 0.01, d: 10.0}       
        joint3_position_controller:
               type: effort_controllers/JointPositionController
               joint: Joint_3
               pid: {p: 100, i: 0.01, d: 10.0}       
        joint4_position_controller:
               type: effort_controllers/JointPositionController
               joint: Joint_4
               pid: {p: 100, i: 0.01, d: 10.0}
        joint5_position_controller:
               type: effort_controllers/JointPositionController
               joint: Joint_5
               pid: {p: 3, i: 0.01, d: 1.3}
