controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint1
    pid:
      {
        p: 500,
        i: 0.0,
        d: 0,
        i_clamp_max: 600,
        i_clamp_min: -600,
        antiwindup: true,
      }
  joint1_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: joint1
    pid: { p: 2.0, i: 0, d: 0.05, i_max: 5.0, i_min: -5.0, antiwindup: true }
