chassis: 
  chassis_controller:
    # the controller you use
    type: "chassis_controller/SwerveWheel"
    
    # the essential param START here
    publish_rate: 100
    power:
      effort_coeff: 12.0
      vel_coeff: 0.0048
      power_offset: -3
    twist_angular: 0.5233
    timeout: 0.1
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]

    wheel_base: 0.356
    wheel_track: 0.356
    wheel_radius: 0.0575
    # the essential param END here

    # DON'T change the ns "left_front_heading" "right_front_driving" U.S.W
    heading_left_front:
    # change the joint name, make it the same as URDF
      joint: "heading_left_front_joint"
      pid:
        {
          p: 2.0,
          i: 0.1,
          d: 0.4,
          i_max: 0.0,
          i_min: 0.0,
          antiwindup: true,
          publish_state: true,
        }
    heading_right_front:
      joint: "heading_right_front_joint"
      pid:
        {          
          p: 2.0,
          i: 0.1,
          d: 0.4,
          i_max: 0.0,
          i_min: 0.0,
          antiwindup: true,
          publish_state: true,
        }
    heading_left_back:
      joint: "heading_left_back_joint"
      pid:
        {
          p: 2.0,
          i: 0.1,
          d: 0.4,
          i_max: 0.0,
          i_min: 0.0,
          antiwindup: true,
          publish_state: true,
        }
    heading_right_back:
      joint: "heading_right_back_joint"
      pid:
        {
          p: 2.0,
          i: 0.1,
          d: 0.4,
          i_max: 0.0,
          i_min: 0.0,
          antiwindup: true,
          publish_state: true,
        }

    driving_left_front:
      joint: "driving_left_front_joint"
      pid:
        {
          p: 0.8,
          i: 0,
          d: 0.0,
          i_max: 0.0,
          i_min: 0.0,
          antiwindup: true,
          publish_state: true,
        }
    driving_right_front:
      joint: "driving_right_front_joint"
      pid:
        {
          p: 0.8,
          i: 0,
          d: 0.0,
          i_max: 0.0,
          i_min: 0.0,
          antiwindup: true,
          publish_state: true,
        }
    driving_left_back:
      joint: "driving_left_back_joint"
      pid:
        {
          p: 0.8,
          i: 0,
          d: 0.0,
          i_max: 0.0,
          i_min: 0.0,
          antiwindup: true,
          publish_state: true,
        }
    driving_right_back:
      joint: "driving_right_back_joint"
      pid:
        {
          p: 0.8,
          i: 0,
          d: 0.0,
          i_max: 0.0,
          i_min: 0.0,
          antiwindup: true,
          publish_state: true,
        }
