gimbal:
  gimbal_controller:
    type: "gimbal_controller/GimbalEngineer"
    publish_rate: 100
    timeout: 0.1

    yaw:
      joint: "gimbal_yaw_joint"
      pid: { p: 8.0, i: 0, d: 0.8, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    pitch:
      joint: "gimbal_pitch_joint"
      pid: { p: 1.0, i: 0, d: 0.0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    
   
