joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 300
arm:
  arm_joint_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    gains:
      joint1: { p: 5, i: 0.0, d: 0.0, i_clamp: 0.0 }
      joint2: { p: 500, i: 0.0, d: 0.0, i_clamp: 0.0 }
      joint3: { p: 300, i: 0.0, d: 0.0, i_clamp: 0.0 }
      joint4: { p: 5, i: 0.0, d: 0.0, i_clamp: 0.0 }
      joint5: { p: 80, i: 0.0, d: 0.0, i_clamp: 0.0 }
      joint6: { p: 5, i: 0.0, d: 0.0, i_clamp: 0.0 }

  arm_gripper_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - joint7
    gains:
      joint7: { p: 10, i: 0.0, d: 0.0, i_clamp: 0.0 }
