joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 300
arm:
  arm_joint_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
    gains:
      joint1: { p: 2700, i: 400.0, d: 280.0, i_clamp: 100.0 }
      joint2: { p: 520, i: 30.0, d: 65.0, i_clamp: 100.0 }
      joint3: { p: 520, i: 30.0, d: 65.0, i_clamp: 100.0 }
      joint4: { p: 380, i: 30.0, d: 65.0, i_clamp: 100.0 }
      joint5: { p: 50, i: 5, d: 1, i_clamp: 5.0 }
      joint6: { p: 70, i: 8, d: 6, i_clamp: 50.0 }
      joint7: { p: 100, i: 5 , d: 7, i_clamp: 20.0 }


