bus:
  - can3
  - can4
  - can5
loop_frequency: 800
cycle_time_error_threshold: 1
thread_priority: 30

actuators:
  left_front_wheel_motor:
    bus: can3
    id: 0x201
    type: rm_3508

  left_back_wheel_motor:
    bus: can3
    id: 0x202
    type: rm_3508

  right_back_wheel_motor:
    bus: can3
    id: 0x203
    type: rm_3508

  right_front_wheel_motor:
    bus: can3
    id: 0x204
    type: rm_3508

  z_joint_left_motor:
    bus: can4
    id: 0x201
    type: rm_3508
  z_joint_right_motor:
    bus: can4
    id: 0x202
    type: rm_3508
  x_joint_left_motor:
    bus: can4
    id: 0x203
    type: rm_3508
  x_joint_right_motor:
    bus: can4
    id: 0x204
    type: rm_3508
  y_joint_motor:
    bus: can5
    id: 0x205
    type: rm_3508
  yaw_joint_motor:
    bus: can5
    id: 0x004
    type: DM_J4310
  roll1_joint_motor:
    bus: can5
    id: 0x005
    type: DM_J4310
  pitch_joint_motor:
    bus: can5
    id: 0x206
    type: rm_2006
  roll2_joint_motor:
    bus: can5
    id: 0x207
    type: rm_2006
  ore_left_joint_motor:
    bus: can4
    id: 0x206
    type: rm_2006
  ore_right_joint_motor:
    bus: can4
    id: 0x207
    type: rm_2006

  gimbal_yaw_joint_motor:
    bus: can5
    id: 0x208
    type: rm_2006

  gimbal_pitch_joint_motor:
    bus: can5
    id: 0x101
    type: MG_996R
  
gpios:

  pump_gpio:
    bus: can4
    id: 0x101
    type: out

  rod_gpio:
    bus: can4
    id: 0x102
    type: out

  joint_z_gpio:
    bus: can4
    id: 0x105
    type: out

  joint_x_gpio:
    bus: can4
    id: 0x106
    type: out

  joint_y_gpio:
    bus: can5
    id: 0x107
    type: out
    
  joint_pitch_gpio:
    bus: can5
    id: 0x108
    type: out


