bus:
  - can4
  - can5
loop_frequency: 800
cycle_time_error_threshold: 1
thread_priority: 30

actuators:
  mast_joint_motor:
    bus: can4
    id: 0x207
    type: rm_2006

  fpv_yaw_joint_motor:
    bus: can5
    id: 0x101
    type: MG_995

  fpv_pitch_joint_motor:
    bus: can5
    id: 0x102
    type: MG_995
