bus:
  - can0
loop_frequency: 1000
cycle_time_error_threshold: 1
thread_priority: 30

actuators:
  motor1:
    bus: can0
    id: 0x205
    type: rm_3508

  motor2:
    bus: can0
    id: 0x206
    type: rm_3508

gpios:
  joint1_gpio:
    bus: can0
    id: 0x101
    type: out
    value: false



