bus:
  - can0
loop_frequency: 800
cycle_time_error_threshold: 1
thread_priority: 30

actuators:
  joint1_motor:
    bus: can0
    id: 0x001
    type: DM_J4310
  
  joint2_motor:
    bus: can0
    id: 0x142
    type: MG_8016

  joint3_motor:
    bus: can0
    id: 0x143
    type: MG_8016

  joint4_motor:
    bus: can0
    id: 0x004
    type: DM_J4310
  
  joint5_motor:
    bus: can0
    id: 0x005
    type: DM_J4310
  
  joint6_motor:
    bus: can0
    id: 0x006
    type: DM_J4310

  joint7_motor:
    bus: can0
    id: 0x207
    type: rm_2006
