bus:
  - can1
loop_frequency: 800
cycle_time_error_threshold: 1
thread_priority: 30

actuators:
  mast_joint_motor:
    bus: can1
    id: 0x206
    type: rm_2006

  fpv_yaw_joint_motor:
    bus: can1
    id: 0x101
    type: MG_995

  fpv_pitch_joint_motor:
    bus: can1
    id: 0x102
    type: MG_995
