bus:
  - can0
loop_frequency: 800
cycle_time_error_threshold: 1
thread_priority: 30

actuators:
  joint1_left_motor:
    bus: can0
    id: 0x201
    type: rm_3508

  joint1_right_motor:
    bus: can0
    id: 0x202
    type: rm_3508
  
  joint2_left_motor:
    bus: can0
    id: 0x203
    type: rm_3508

  joint2_right_motor:
    bus: can0
    id: 0x204
    type: rm_3508

  joint3_left_motor:
    bus: can0
    id: 0x205
    type: rm_3508

  joint3_right_motor:
    bus: can0
    id: 0x206
    type: rm_3508

  joint4_motor:
    bus: can0
    id: 0x207
    type: rm_3508

  joint5_motor:
    bus: can0
    id: 0x005
    type: DM_J4310
  
  joint6_motor:
    bus: can0
    id: 0x006
    type: DM_J4310

  joint7_motor:
    bus: can0
    id: 0x007
    type: DM_J4310
