bus:
  - can0
loop_frequency: 1000
cycle_time_error_threshold: 1
thread_priority: 30

actuators:
  motor1:
    bus: can0
    id: 0x202
    type: rm_2006

  motor2:
    bus: can0
    id: 0x204
    type: rm_2006


gpios:
  joint1_gpio:
    bus: can0
    id: 0x101
    type: out
    value: false



