bus:
  - can0
loop_frequency: 650
cycle_time_error_threshold: 1
thread_priority: 65

actuators:
  joint1_motor:
    bus: can0
    id: 0x001
    type: DM_J4310

  joint2_motor:
    bus: can0
    id: 0x142
    type: MG_8016

  joint3_motor:
    bus: can0
    id: 0x141
    type: MG_8016

  joint4_motor:
    bus: can0
    id: 0x004
    type: DM_J4310
