bus:
  - can0

loop_frequency: 800
cycle_time_error_threshold: 1
thread_priority: 30

actuators:
  right_front_wheel_motor:
    bus: can0
    id: 0x211
    type: rm_3508

  right_back_wheel_motor:
    bus: can0
    id: 0x212
    type: rm_3508

  left_back_wheel_motor:
    bus: can0
    id: 0x213
    type: rm_3508

  left_front_wheel_motor:
    bus: can0
    id: 0x214
    type: rm_3508

  yaw_joint_motor:
    bus: can0
    id: 0x205
    type: rm_3508

  pitch_joint_motor:
    bus: can0
    id: 0x206
    type: rm_3508

  trigger_joint_motor:
    bus: can0
    id: 0x207
    type: rm_2006

  fric_left_joint_motor:
    bus: can0
    id: 0x201
    type: rm_3508

  fric_right_joint_motor:
    bus: can0
    id: 0x202
    type: rm_3508
  
gpios:
  cover:
    bus: can0
    id: 0x101
    type: out

