manipulator:
  manipulator_controller:
    type: "manipulator_controller/ManipulatorController"
    publish_rate: 100
    timeout: 0.1

    z:
      has_friction: false
      friction: 25.0
      has_gravity: true
      gravity: 60.0
# 25 -75 2100 200 2
      left_joint:
        joint: "z_joint_left"
        pid: { p: 1200.0, i: 10.0, d: 50.0, i_max: 100.0, i_min: -100.0, antiwindup: true, publish_state: true }
      right_joint:
        joint: "z_joint_right"
        pid: { p: 1200.0, i: 10.0, d: 50.0, i_max: 100.0, i_min: -100.0, antiwindup: true, publish_state: true }
    x:
      has_friction: false
      friction: 16.0
      has_gravity: false
      gravity: 0.0

      left_joint:
        joint: "x_joint_left"
        pid: { p: 400.0, i: 30.0, d: 65.0, i_max: 200.0, i_min: -200.0, antiwindup: true, publish_state: true }
      right_joint:
        joint: "x_joint_right"
        pid: { p: 400.0, i: 30.0, d: 65.0, i_max: 200.0, i_min: -200.0, antiwindup: true, publish_state: true }

    y:
      has_friction: false
      friction: 7.0

      joint: "y_joint"
      pid: { p: 300.0, i: 4.0, d: 10.0, i_max: 100.0, i_min: -100.0, antiwindup: true, publish_state: true }
    
    yaw:
      joint: "yaw_joint"
      pid: { p: 25.0, i: 0.3, d: 0.01, i_max: 50.0, i_min: -50.0, antiwindup: true, publish_state: true }

    roll1:
      joint: "roll1_joint"
      pid: { p: 6.0, i: 0.0, d: 0.005, i_max: 20.0, i_min: -20.0, antiwindup: true, publish_state: true }

    pitch:
      joint: "pitch_joint"
      pid: { p: 22.0, i: 0.3, d: 0.05, i_max: 10.0, i_min: -10.0, antiwindup: true, publish_state: true }

    roll2:
      joint: "roll2_joint"
      pid: { p: 6.0, i: 0.0, d: 0.005, i_max: 20.0, i_min: -20.0, antiwindup: true, publish_state: true }

    diff:
      differential_reduction: 2
      positive_joint:
        joint: "pitch_joint"
        pid: { p: 1.8, i: 0.02, d: 0.06, i_max: 100.0, i_min: -100.0, antiwindup: true, publish_state: true }
      negative_joint:
        joint: "roll2_joint"
        pid: { p: 1.8, i: 0.02, d: 0.06, i_max: 100.0, i_min: -100.0, antiwindup: true, publish_state: true }



    
      
    

    vel_limit:
      {z: 0.0002, x: 0.0002, y: 0.0001, yaw: 0.00314, roll1: 0.00314, pitch: 0.00314, roll2: 0.00314}
    upper_pos_limit:
      {z: 0.755, x: 0.265, y: 0.25, yaw: 3.14, roll1: 6.28, pitch: 1.57, roll2: 6.28}
    lower_pos_limit:
      {z: 0.0, x: 0.0, y: -0.25, yaw: -3.14, roll: -6.28, pitch: -1.57, roll2: -6.28}
    structure_coeff:
      {l1: 0.60, l2: 0.25, l3: 0.10, l4: 0.20}
    
