manipulator:
  manipulator_controller:
    type: "manipulator_controller/ManipulatorController"
    publish_rate: 100
    timeout: 0.1

    z:
      has_friction: true
      friction: 25.0
      has_gravity: true
      gravity: 60.0
# 25 -75 2100 200 2
      left_joint:
        joint: "joint1_left"
        pid: { p: 1500.0, i: 5.0, d: 5.0, i_max: 100.0, i_min: -100.0, antiwindup: true, publish_state: true }
      right_joint:
        joint: "joint1_right"
        pid: { p: 1500.0, i: 5.0, d: 5.0, i_max: 100.0, i_min: -100.0, antiwindup: true, publish_state: true }
    x1:
      has_friction: true
      friction: 16.0
      has_gravity: false
      gravity: 0.0

      left_joint:
        joint: "joint2_left"
        pid: { p: 400.0, i: 30.0, d: 65.0, i_max: 200.0, i_min: -200.0, antiwindup: true, publish_state: true }
      right_joint:
        joint: "joint2_right"
        pid: { p: 400.0, i: 30.0, d: 65.0, i_max: 200.0, i_min: -200.0, antiwindup: true, publish_state: true }
    x2:
      has_friction: true
      friction: 16.0
      has_gravity: false
      gravity: 0.0

      left_joint:
        joint: "joint3_left"
        pid: { p: 200.0, i: 6.0, d: 17.0, i_max: 100.0, i_min: -100.0, antiwindup: true, publish_state: true }
      right_joint:
        joint: "joint3_right"
        pid: { p: 200.0, i: 6.0, d: 17.0, i_max: 100.0, i_min: -100.0, antiwindup: true, publish_state: true }
    y:
      has_friction: true
      friction: 7.0

      joint: "joint4"
      pid: { p: 400.0, i: 3.0, d: 8.0, i_max: 100.0, i_min: -100.0, antiwindup: true, publish_state: true }

    pitch:
      joint: "joint5"
      pid: { p: 22.0, i: 0.3, d: 0.05, i_max: 10.0, i_min: -10.0, antiwindup: true, publish_state: true }

    yaw:
      joint: "joint6"
      pid: { p: 25.0, i: 0.3, d: 0.01, i_max: 50.0, i_min: -50.0, antiwindup: true, publish_state: true }
      
    roll:
      joint: "joint7"
      pid: { p: 6.0, i: 0.0, d: 0.005, i_max: 20.0, i_min: -20.0, antiwindup: true, publish_state: true }

    vel_limit:
      {z: 0.00005, x1: 0.0002, x2: 0.0002, y: 0.0001, pitch: 0.0005, yaw: 0.0005, roll: 0.0005}
    upper_pos_limit:
      {z: 0.0, x1: 0.45, x2: 0.45, y: 0.15, pitch: 1.57, yaw: 1.57, roll: 1.57}
    lower_pos_limit:
      {z: -0.15, x1: 0.0, x2: 0.0, y: -0.15, pitch: -1.57, yaw: -1.57, roll: -1.57}
    structure_coeff:
      {l1: 0.60, l2: 0.25, l3: 0.10, l4: 0.20}
    
