manipulator:
  manipulator_controller:
    type: "manipulator_controller/ManipulatorController"
    publish_rate: 100
    timeout: 0.1

    z:
      has_friction: true
      friction: 16.0
      has_gravity: true
      gravity: 50.0
# 25 -75 2100 200 2
      left_joint:
        joint: "z_joint_left"
        pid: { p: 320.0, i: 0.0, d: 25.0, i_max: 100.0, i_min: -100.0, antiwindup: true, publish_state: true }
      right_joint:
        joint: "z_joint_right"
        pid: { p: 320.0, i: 0.0, d: 25.0, i_max: 100.0, i_min: -100.0, antiwindup: true, publish_state: true }
    x:
      has_friction: true
      friction: 34.0
      has_gravity: false
      gravity: 0.0

      left_joint:
        joint: "x_joint_left"
        pid: { p: 55.0, i: 0.0, d: 8.0, i_max: 200.0, i_min: -200.0, antiwindup: true, publish_state: true }
      right_joint:
        joint: "x_joint_right"
        pid: { p: 55.0, i: 0.0, d: 8.0, i_max: 200.0, i_min: -200.0, antiwindup: true, publish_state: true }

    y:
      has_friction: true
      friction: 8.0

      joint: "y_joint"
      pid: { p: 45.0, i: 0.1, d: 15.5 , i_max: 100.0, i_min: -100.0, antiwindup: true, publish_state: true }
      #lock_pid: { p: 2400.0, i: 0.5, d: 50.0 , i_max: 100.0, i_min: -100.0, antiwindup: true, publish_state: true }
      lock_pid: { p: 24.0, i: 0.5, d: 10.0 , i_max: 100.0, i_min: -100.0, antiwindup: true, publish_state: true }
    
    yaw:
      joint: "yaw_joint"
      pid: { p: 19.0, i: 0.3, d: 0.2, i_max: 50.0, i_min: -50.0, antiwindup: true, publish_state: true }

    roll1:
      joint: "roll1_joint"
      pid: { p: 13.0, i: 0.01, d: 0.06, i_max: 20.0, i_min: -20.0, antiwindup: true, publish_state: true }

    pitch:
      joint: "pitch_joint"
      pid: { p: 22.0, i: 0.3, d: 0.05, i_max: 10.0, i_min: -10.0, antiwindup: true, publish_state: true }

    roll2:
      joint: "roll2_joint"
      pid: { p: 6.0, i: 0.0, d: 0.005, i_max: 20.0, i_min: -20.0, antiwindup: true, publish_state: true }

    diff:
      differential_reduction: 2
      positive_joint:
        joint: "pitch_joint"
        pid: { p: 2.2, i: 0.05, d: 0.06, i_max: 100.0, i_min: -100.0, antiwindup: true, publish_state: true }
      negative_joint:
        joint: "roll2_joint"
        pid: { p: 2.2, i: 0.05, d: 0.06, i_max: 100.0, i_min: -100.0, antiwindup: true, publish_state: true }
      pitch_pid:
        pid: { p: 17.5, i: 1.2, d: 0.3, i_max: 1.0, i_min: -1.0, antiwindup: true, publish_state: true }
      roll_pid:
        pid: { p: 2.0, i: 0.00, d: 0.05, i_max: 1.0, i_min: -1.0, antiwindup: true, publish_state: true }
     
    

    vel_limit:
      {1_z: 0.25, 2_x: 0.15, 3_y: 0.2, 4_yaw: 1.57, 5_roll1: 3.14, 6_pitch: 3.14, 7_roll2: 3.14}
    upper_pos_limit:
      {1_z: 0.700, 2_x: 0.22, 3_y: 0.25, 4_yaw: 2.00, 5_roll1: 6.28, 6_pitch: 3.00, 7_roll2: 6.28}
    lower_pos_limit:
      {1_z: -0.120, 2_x: -0.22, 3_y: -0.25, 4_yaw: -2.00, 5_roll1: -6.28, 6_pitch: -3.00, 7_roll2: -6.28}
    position_threshold:
      {1_z: 0.008, 2_x: 0.005, 3_y: 0.005, 4_yaw: 0.03, 5_roll1: 0.05, 6_pitch: 0.3, 7_roll2: 0.05}
    structure_coeff:
      {l1: 0.60, l2: 0.25, l3: 0.10, l4: 0.20}

    destination:
      home:
        {1_z: 0.1, 2_x: 0.0, 3_y: 0.0, 4_yaw: 1.57, 5_roll1: 0.0, 6_pitch: 1.4, 7_roll2: 0.0}
      ground:
        {1_z: 0.205, 2_x: 0.0, 3_y: 0.1, 4_yaw: 0.0, 5_roll1: 0.0, 6_pitch: -1.57, 7_roll2: 0.0}
      sliver:
        {1_z: 0.205, 2_x: 0.0, 3_y: -0.20, 4_yaw: 0.0, 5_roll1: 0.0, 6_pitch: -1.57, 7_roll2: 0.0}#z:0.347
      gold:
        {1_z: 0.125, 2_x: 0.0, 3_y: 0.0, 4_yaw: 0.0, 5_roll1: 0.0, 6_pitch: 0.00, 7_roll2: 0.0}#z:0.148
      exchange:
        {1_z: 0.60, 2_x: 0.0, 3_y: 0.22, 4_yaw: 0.0, 5_roll1: 0.0, 6_pitch: 0.00, 7_roll2: 0.0}
    
    process:
      take_sliver:
        process_num: 4
        destinations:
        -  {1_z: 0.50, 2_x: 0.00, 3_y: -0.20, 4_yaw: 0.0, 5_roll1: 0.0, 6_pitch: -1.57, 7_roll2: 0.0}
        -  {1_z: 0.50, 2_x: 0.00, 3_y: 0.05, 4_yaw: 0.0, 5_roll1: 0.0, 6_pitch: -1.57, 7_roll2: 0.0}
        -  {1_z: 0.44, 2_x: 0.00, 3_y: 0.05, 4_yaw: 0.0, 5_roll1: 0.0, 6_pitch: -1.57, 7_roll2: 0.0}
        -  {1_z: 0.60, 2_x: 0.00, 3_y: 0.05, 4_yaw: 0.0, 5_roll1: 0.0, 6_pitch: -1.57, 7_roll2: 0.0}  
        delay_time: 0.5
    
      take_gold: 
        process_num: 5
        destinations:
        -  {1_z: 0.125, 2_x: 0.0, 3_y: 0.15, 4_yaw: 0.0, 5_roll1: 0.0, 6_pitch: 0.0, 7_roll2: 0.0}
        -  {1_z: 0.188, 2_x: 0.0, 3_y: 0.15, 4_yaw: 0.0, 5_roll1: 0.0, 6_pitch: 0.0, 7_roll2: 0.0}
        -  {1_z: 0.188, 2_x: 0.0, 3_y: 0.06, 4_yaw: 0.0, 5_roll1: 0.0, 6_pitch: 0.0, 7_roll2: 0.0}
        -  {1_z: 0.145, 2_x: 0.0, 3_y: 0.06, 4_yaw: 0.0, 5_roll1: 0.0, 6_pitch: 0.0, 7_roll2: 0.0}
        -  {1_z: 0.145, 2_x: 0.0, 3_y: -0.02, 4_yaw: 0.0, 5_roll1: 0.0, 6_pitch: 0.0, 7_roll2: 0.0}
        delay_time: 1.0
    
